# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [53]:
# Create a 1-dimensional NumPy array using np.array()

one_dimensional = np.array([100, 200, 300, 400, 500] )
# Create a 2-dimensional NumPy array using np.array()
two_dimensional = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# Create a 3-dimensional Numpy array using np.array()
three_dimensional = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
three_dimensional

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [54]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(one_dimensional.shape)
print(one_dimensional.ndim)
print(one_dimensional.dtype)
print(one_dimensional.size)
print(type(one_dimensional))

(5,)
1
int32
5
<class 'numpy.ndarray'>


In [55]:
# Attributes of 2-dimensional array
# number of dimensions, data type, size and type)
print(two_dimensional.shape)
print(two_dimensional.ndim)
print(two_dimensional.dtype)
print(two_dimensional.size)
print(type(two_dimensional))

(3, 4)
2
int32
12
<class 'numpy.ndarray'>


In [56]:
# Attributes of 3-dimensional array
# number of dimensions, data type, size and type)
print(three_dimensional.shape)
print(three_dimensional.ndim)
print(three_dimensional.dtype)
print(three_dimensional.size)
print(type(three_dimensional))

(2, 3, 4)
3
int32
24
<class 'numpy.ndarray'>


In [57]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(data=  one_dimensional)
df

0
0  100
1  200
2  300
3  400
4  500

In [58]:
# Create an array of shape (10, 2) with only ones
arr_ones = np.ones((10, 2))
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [59]:
# Create an array of shape (7, 2, 3) of only zeros
array = np.zeros((7, 2, 3))
array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [60]:
# Create an array within a range of 0 and 100 with step 3
array_range = np.arange(0,100,3)
array_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [61]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_random_int = np.random.randint(0,10,size= (7,2))
array_random_int

array([[8, 0],
       [9, 2],
       [6, 3],
       [8, 2],
       [4, 2],
       [6, 4],
       [8, 6]])

In [62]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array_random_float = np.random.rand(3, 5)
array_random_float


array([[0.01326496, 0.94220176, 0.56328822, 0.3854165 , 0.01596625],
       [0.23089383, 0.24102547, 0.68326352, 0.60999666, 0.83319491],
       [0.17336465, 0.39106061, 0.18223609, 0.75536141, 0.42515587]])

In [63]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array_random_seed = np.random.randint(0,10,size= (4,6))
array_random_seed

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?
**the numbers ths same**

Are the numbers in the array different or the same? Why do think this is?
**same , because value is the same to 42**

In [108]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array_random_variable= np.random.randint(1,10,size= (3,7))
# Find the unique numbers in the array you just created
unique = np.unique(array_random_variable)
unique

array([1, 2, 3, 4, 5, 6, 7, 8])

In [109]:
# Find the 0'th index of the latest array you created
array_random_variable[0]

array([1, 4, 7, 2, 3, 1, 5])

In [110]:
# Get the first 2 rows of latest array you created
print(array_random_variable[0])
print(array_random_variable[1])

[1 4 7 2 3 1 5]
[1 8 1 1 2 2 6]


In [115]:
# Get the first 2 values of the first 2 rows of the latest array
print(array_random_variable[0][0:2])
print(array_random_variable[1][0:2])


[1 4]
[1 8]


In [5]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array_random1= np.random.randint(1,10,size= (3,5))
array_ones1 =np.ones((3,5))

In [9]:
# Add the two arrays together
add = np.add(array_random1,array_ones1)
print(add)


[[8. 3. 6. 5. 6.]
 [4. 4. 3. 5. 2.]
 [3. 2. 2. 3. 9.]]


In [10]:
# Create another array of ones of shape (5, 3)
array_ones2 = np.ones((5,3))
array_ones2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Try add the array of ones and the other most recent array together
add2 = np.add(add,array_ones2)
print(add2)

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?**will do reshape**

In [12]:
# Create another array of ones of shape (3, 5)
array_ones3 = np.ones((3,5))

In [14]:
# Subtract the new array of ones from the other most recent array
sub = np.subtract(array_ones3,array_random1)
sub

array([[-6., -1., -4., -3., -4.],
       [-2., -2., -1., -3.,  0.],
       [-1.,  0.,  0., -1., -7.]])

In [21]:
# Multiply the ones array with the latest array
mul = np.multiply(array_ones3,array_random1)
print(mul)

[[7. 2. 5. 4. 5.]
 [3. 3. 2. 4. 1.]
 [2. 1. 1. 2. 8.]]


In [23]:
# Take the latest array to the power of 2 using '**'
power = array_random1**2
power

array([[49,  4, 25, 16, 25],
       [ 9,  9,  4, 16,  1],
       [ 4,  1,  1,  4, 64]], dtype=int32)

In [24]:
# Do the same thing with np.square()
np.square(array_random1)

array([[49,  4, 25, 16, 25],
       [ 9,  9,  4, 16,  1],
       [ 4,  1,  1,  4, 64]], dtype=int32)

In [25]:
# Find the mean of the latest array using np.mean()
np.mean(array_random1)

3.3333333333333335

In [26]:
# Find the maximum of the latest array using np.max()
np.max(array_random1)

8

In [27]:
# Find the minimum of the latest array using np.min()
np.min(array_random1)

1

In [28]:
# Find the standard deviation of the latest array
np.std(array_random1)

2.086996778999804

In [29]:
# Find the variance of the latest array
np.var(array_random1)

4.355555555555555

In [30]:
# Reshape the latest array to (3, 5, 1)
array_random1.reshape(3,5,1)

array([[[7],
        [2],
        [5],
        [4],
        [5]],

       [[3],
        [3],
        [2],
        [4],
        [1]],

       [[2],
        [1],
        [1],
        [2],
        [8]]])

In [34]:
# Transpose the latest array
print(np.transpose(array_random1))

[[7 3 2]
 [2 3 1]
 [5 2 1]
 [4 4 2]
 [5 1 8]]


What does the transpose do?**make rows to colums and vice versa**

In [35]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_random2= np.random.randint(0,10,size= (3,3))
array_random3= np.random.randint(0,10,size= (3,2))





In [36]:
# Perform a dot product on the two newest arrays you created
np.dot(array_random2, array_random3)

array([[64, 74],
       [94, 84],
       [68, 68]])

In [37]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_random4= np.random.randint(0,10,size= (4,3))
array_random5= np.random.randint(0,10,size= (4,3))


In [38]:
# Perform a dot product on the two newest arrays you created
np.dot(array_random4, array_random5)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?**by transpose**

In [39]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
transpose_array = np.transpose(array_random4)
np.dot(transpose_array ,array_random5)


array([[101,  30, 111],
       [132,  82, 138],
       [ 74,  11,  75]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [40]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_random6= np.random.randint(0,10,size= (3,3))
array_random7= np.random.randint(0,10,size= (3,3))



In [41]:
# Compare the two arrays with '>'
array_random6>array_random7

array([[False, False, False],
       [False, False, False],
       [False,  True, False]])

What happens when you compare the arrays with `>`?**he compare each elemnt with another element

In [42]:
# Compare the two arrays with '>='
array_random6>=array_random7

array([[False, False, False],
       [False, False,  True],
       [False,  True, False]])

In [43]:
# Find which elements of the first array are greater than 7
array_random6>7

array([[False, False, False],
       [False, False, False],
       [False,  True, False]])

In [44]:
# Which parts of each array are equal? (try using '==')
array_random6==array_random7

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [50]:
# Sort one of the arrays you just created in ascending order
np.sort(array_random7)

array([[7, 9, 9],
       [2, 8, 9],
       [3, 5, 8]])

In [51]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_random7)

array([[0, 1, 2],
       [2, 0, 1],
       [2, 1, 0]], dtype=int64)

In [55]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array_random7)

1

In [56]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array_random7)

5

In [57]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array_random7,axis=1)

array([1, 1, 0], dtype=int64)

In [58]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(array_random7,axis=0)

array([1, 0, 0], dtype=int64)

In [59]:
# Create an array of normally distributed random numbers
np.random.normal(0.0, 1.0, 5)

array([ 0.32629761,  0.06431494, -1.12647584, -0.99641564, -0.49872003])

In [60]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.